#pragma config(Motor,  port9,           rightmotor,    tmotorVex393, openLoop)
#pragma config(Motor,  port3,           claw,          tmotorVex393, openLoop)
#pragma config(Motor,  port7,           arm,           tmotorVex393, openLoop)
#pragma config(Motor,  port2,           leftmotor,     tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
LEFT JOYSTICK: Left Motor Forward/Back
RIGHT JOYSTICK: Right Motor Forward/Back
RIGHT BOT BUMP: Arm Down
RIGHT TOP BUMP: Arm Up
LEFT BOT BUMP: Claw Out
RIGHT BOT BUMP: Claw in
BUTTON 8R: Terminate Program
BUTTON 8D: Path On/Off
BUTTON 7U: Path: Permanente Forward
BUTTON 7D: Path: Permanente Backward
BUTTON 7L: Path: Permanente Circle Left
BUTTON 7R: Path: Permanente Circle Right
BUTTON 8L: Path: Permanente Arm Jerk
BUTTON 8U: Path: Permanente Claw Jerk
*/
task main(){
	while(true){
	//_________________________________________________________________
		//Tank Control on Wheels
		motor[leftmotor]=vexRT(Ch3)/2;
		motor[rightmotor]=vexRT(Ch2)/2;
	//_________________________________________________________________
		//Arm moves on bumper press
		if(vexRT[Btn6U] == 1){motor[arm] = 35;}
  	else if(vexRT[Btn6D] == 1){motor[arm] = -30;}
  	else{motor[arm] = 0;}
  //_________________________________________________________________
  	//Claw moves on bumper press
  	if(vexRT[Btn5U] == 1){motor[claw] = 35;}
  	else if(vexRT[Btn5D] == 1){motor[claw] = -30;}
  	else{motor[claw] = 0;}
  //_________________________________________________________________
  	//Terminate program on 8R press
  	if(vexRT[Btn8R] == 1){break;}
  //_________________________________________________________________
  		//Straight Line Forward
			if(vexRT[Btn7U] == 1){
  			while(true){motor[leftmotor] = 127;motor[rightmotor] = 127;wait1Msec(1000);
  				if(vexRT[Btn7U] == 1){motor[leftmotor]=0;motor[rightmotor]=0;break;}}
  		}
  		//Straight Line Backward
  		else if(vexRT[Btn7D] == 1){
  			while(true){motor[leftmotor] = -127;motor[rightmotor] = -127;wait1Msec(10000);
  				if(vexRT[Btn7D] == 1){motor[leftmotor]=0;motor[rightmotor]=0;break;}}
  		}
  		//Circle Right
  		else if(vexRT[Btn7R] == 1){
  			while(true){motor[leftmotor] = 50;motor[rightmotor] = 127;;wait1Msec(10000);
  				if(vexRT[Btn7R] == 1){motor[leftmotor]=0;motor[rightmotor]=0;break;}}
  		}
  		//Circle Left
  		else if(vexRT[Btn7L] == 1){
  			while(true){motor[leftmotor] = 127;motor[rightmotor] = 50;wait1Msec(10000);
  				if(vexRT[Btn7L] == 1){motor[leftmotor]=0;motor[rightmotor]=0;break;}}
  		}
  		//Arm Jerk
  		else if(vexRT[Btn8L] == 1){
  			while(true){motor[arm] = 100;wait1Msec(1000);motor[arm] = -100;wait1Msec(1000);
  				motor[leftmotor]=vexRT(Ch3)/2;
					motor[rightmotor]=vexRT(Ch2)/2;
  				if(vexRT[Btn8L] == 1){motor[arm]=0;break;}}
  		}
  		//STOP
  		else if(vexRT[Btn8U] == 1){
  			motor[leftmotor]=0;motor[rightmotor]=0;motor[claw]=0;motor[arm]=0;wait1Msec(1000);
  		}
//task main bracket
}
}
