#pragma config(Motor,  port9,           rightmotor,    tmotorVex393, openLoop)
#pragma config(Motor,  port3,           claw,          tmotorVex393, openLoop)
#pragma config(Motor,  port7,           arm,           tmotorVex393, openLoop)
#pragma config(Motor,  port2,           leftmotor,     tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Sentry Program
//47.5x82.5 (including buffer)
void longside(){
	motor[leftmotor]=127;
	motor[rightmotor]=80;
	wait1Msec(3900);
}
void shortside(){
	motor[leftmotor]=127;
	motor[rightmotor]=80;
	wait1Msec(2240);
}
void turn(){
	motor[leftmotor]=-20;
	motor[rightmotor]=100;
	wait1Msec(1000);
}
task main(){
	while(true){
		longside();
		turn();
		shortside();
		turn();
	}
}
